### ISSUE TITLE
expected scalar type Double but found Float

### ISSUE THREAD

**Issue by StarMi0** [weixmath/view-GCN#15]
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    trainer.update_validation_accuracy(1)
  File "/media/user/data/render_data/#/viev_GCN/tools/Trainer.py", line 125, in update_validation_accuracy
    out_data,F1,F2=self.model(in_data)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/user/data/render_data/#/viev_GCN/model/view_gcn.py", line 128, in forward
    y = self.LocalGCN1(y,vertices)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/user/data/render_data/#/viev_GCN/tools/view_gcn_utils.py", line 121, in forward
    F = self.KNN(F, V)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/user/data/render_data/#/viev_GCN/tools/view_gcn_utils.py", line 77, in forward
    v_F = self.R(v_F)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: expected scalar type Double but found Float

Faced such a problem, is it in the version of python? I have 3.7

**Comment by weixmath** [comment]
Can you check the type of each variable?  Especially the type of "vertices".

**Comment by auniquesun** [comment]
> vertices

I came across the same error "RuntimeError: expected scalar type Double but found Float". 

I have set `self.vertices = torch.tensor(vertices, dtype=torch.float64).cuda()`, but the error occurred again.
