### ISSUE TITLE
AttributeError: 'int' object has no attribute 'float'

### ISSUE THREAD

**Issue by daqing91386282** [weixmath/view-GCN#21]
# Thank you very much for providing the code. Why can the training result fail after running and the data type error? Is it my operation mode problem?
## AttributeError：
WARNING: summary folder already exists!! It will be overwritten!!
WARNING: summary folder already exists!! It will be overwritten!!
num_train_files: 0
num_val_files: 0
.\view-GCN-master\model\Trainer.py:137: RuntimeWarning: invalid value encountered in divide
  class_acc = (samples_class - wrong_class) / samples_class
Traceback (most recent call last):
  File ".\view-GCN-master/model/train.py", line 65, in <module> trainer.train(30)
  File ".\view-GCN-master\model\Trainer.py", line 89, in train loss, val_overall_acc, val_mean_class_acc = self.update_validation_accuracy(epoch)
  File ".\view-GCN-master\model\Trainer.py", line 139, in update_validation_accuracy  acc = all_correct_points.float() / all_points
AttributeError: 'int' object has no attribute 'float'
Total # of test models:  0

if the will trainer.train(30)_[train.py]_revisetrainer.train(0)
num_train_files: 0
num_val_files: 0
WARNING: summary folder already exists!! It will be overwritten!!
num_train_files: 0
num_val_files: 0

no  training data was available.

**Comment by weixmath** [comment]
please check the path of the dataset.
